namespace Godot.Net.Servers.Rendering;

public abstract partial class RenderingDevice
{
    public enum RenderPrimitive
    {
        RENDER_PRIMITIVE_POINTS,
        RENDER_PRIMITIVE_LINES,
        RENDER_PRIMITIVE_LINES_WITH_ADJACENCY,
        RENDER_PRIMITIVE_LINESTRIPS,
        RENDER_PRIMITIVE_LINESTRIPS_WITH_ADJACENCY,
        RENDER_PRIMITIVE_TRIANGLES,
        RENDER_PRIMITIVE_TRIANGLES_WITH_ADJACENCY,
        RENDER_PRIMITIVE_TRIANGLE_STRIPS,
        RENDER_PRIMITIVE_TRIANGLE_STRIPS_WITH_AJACENCY,
        RENDER_PRIMITIVE_TRIANGLE_STRIPS_WITH_RESTART_INDEX,
        RENDER_PRIMITIVE_TESSELATION_PATCH,
        RENDER_PRIMITIVE_MAX
    };
}
