namespace Godot.Net.Servers.Rendering;

public abstract partial class RenderingDevice
{
    public enum DriverResource
    {
        DRIVER_RESOURCE_VULKAN_DEVICE = 0,
        DRIVER_RESOURCE_VULKAN_PHYSICAL_DEVICE,
        DRIVER_RESOURCE_VULKAN_INSTANCE,
        DRIVER_RESOURCE_VULKAN_QUEUE,
        DRIVER_RESOURCE_VULKAN_QUEUE_FAMILY_INDEX,
        DRIVER_RESOURCE_VULKAN_IMAGE,
        DRIVER_RESOURCE_VULKAN_IMAGE_VIEW,
        DRIVER_RESOURCE_VULKAN_IMAGE_NATIVE_TEXTURE_FORMAT,
        DRIVER_RESOURCE_VULKAN_SAMPLER,
        DRIVER_RESOURCE_VULKAN_DESCRIPTOR_SET,
        DRIVER_RESOURCE_VULKAN_BUFFER,
        DRIVER_RESOURCE_VULKAN_COMPUTE_PIPELINE,
        DRIVER_RESOURCE_VULKAN_RENDER_PIPELINE,
        //next driver continue enum from 1000 to keep order
    }
}
