namespace Godot.Net.Servers.Rendering;

#pragma warning disable CA1069

public abstract partial class RenderingDevice
{
    public enum ShaderStage
    {
        SHADER_STAGE_VERTEX,
        SHADER_STAGE_FRAGMENT,
        SHADER_STAGE_TESSELATION_CONTROL,
        SHADER_STAGE_TESSELATION_EVALUATION,
        SHADER_STAGE_COMPUTE,
        SHADER_STAGE_MAX,
        SHADER_STAGE_VERTEX_BIT = 1 << SHADER_STAGE_VERTEX,
        SHADER_STAGE_FRAGMENT_BIT = 1 << SHADER_STAGE_FRAGMENT,
        SHADER_STAGE_TESSELATION_CONTROL_BIT = 1 << SHADER_STAGE_TESSELATION_CONTROL,
        SHADER_STAGE_TESSELATION_EVALUATION_BIT = 1 << SHADER_STAGE_TESSELATION_EVALUATION,
        SHADER_STAGE_COMPUTE_BIT = 1 << SHADER_STAGE_COMPUTE,
    }
}
