namespace Godot.Net.Servers;
public abstract partial class RenderingServer
{
    public enum GlobalShaderParameterType
    {
        GLOBAL_VAR_TYPE_BOOL,
        GLOBAL_VAR_TYPE_BVEC2,
        GLOBAL_VAR_TYPE_BVEC3,
        GLOBAL_VAR_TYPE_BVEC4,
        GLOBAL_VAR_TYPE_INT,
        GLOBAL_VAR_TYPE_IVEC2,
        GLOBAL_VAR_TYPE_IVEC3,
        GLOBAL_VAR_TYPE_IVEC4,
        GLOBAL_VAR_TYPE_RECT2I,
        GLOBAL_VAR_TYPE_UINT,
        GLOBAL_VAR_TYPE_UVEC2,
        GLOBAL_VAR_TYPE_UVEC3,
        GLOBAL_VAR_TYPE_UVEC4,
        GLOBAL_VAR_TYPE_FLOAT,
        GLOBAL_VAR_TYPE_VEC2,
        GLOBAL_VAR_TYPE_VEC3,
        GLOBAL_VAR_TYPE_VEC4,
        GLOBAL_VAR_TYPE_COLOR,
        GLOBAL_VAR_TYPE_RECT2,
        GLOBAL_VAR_TYPE_MAT2,
        GLOBAL_VAR_TYPE_MAT3,
        GLOBAL_VAR_TYPE_MAT4,
        GLOBAL_VAR_TYPE_TRANSFORM_2D,
        GLOBAL_VAR_TYPE_TRANSFORM,
        GLOBAL_VAR_TYPE_SAMPLER2D,
        GLOBAL_VAR_TYPE_SAMPLER2DARRAY,
        GLOBAL_VAR_TYPE_SAMPLER3D,
        GLOBAL_VAR_TYPE_SAMPLERCUBE,
        GLOBAL_VAR_TYPE_MAX
    }
}
