namespace Godot.Net.Servers;

public abstract partial class RenderingServer
{
    public enum ViewportDebugDraw
    {
        VIEWPORT_DEBUG_DRAW_DISABLED,
        VIEWPORT_DEBUG_DRAW_UNSHADED,
        VIEWPORT_DEBUG_DRAW_LIGHTING,
        VIEWPORT_DEBUG_DRAW_OVERDRAW,
        VIEWPORT_DEBUG_DRAW_WIREFRAME,
        VIEWPORT_DEBUG_DRAW_NORMAL_BUFFER,
        VIEWPORT_DEBUG_DRAW_VOXEL_GI_ALBEDO,
        VIEWPORT_DEBUG_DRAW_VOXEL_GI_LIGHTING,
        VIEWPORT_DEBUG_DRAW_VOXEL_GI_EMISSION,
        VIEWPORT_DEBUG_DRAW_SHADOW_ATLAS,
        VIEWPORT_DEBUG_DRAW_DIRECTIONAL_SHADOW_ATLAS,
        VIEWPORT_DEBUG_DRAW_SCENE_LUMINANCE,
        VIEWPORT_DEBUG_DRAW_SSAO,
        VIEWPORT_DEBUG_DRAW_SSIL,
        VIEWPORT_DEBUG_DRAW_PSSM_SPLITS,
        VIEWPORT_DEBUG_DRAW_DECAL_ATLAS,
        VIEWPORT_DEBUG_DRAW_SDFGI,
        VIEWPORT_DEBUG_DRAW_SDFGI_PROBES,
        VIEWPORT_DEBUG_DRAW_GI_BUFFER,
        VIEWPORT_DEBUG_DRAW_DISABLE_LOD,
        VIEWPORT_DEBUG_DRAW_CLUSTER_OMNI_LIGHTS,
        VIEWPORT_DEBUG_DRAW_CLUSTER_SPOT_LIGHTS,
        VIEWPORT_DEBUG_DRAW_CLUSTER_DECALS,
        VIEWPORT_DEBUG_DRAW_CLUSTER_REFLECTION_PROBES,
        VIEWPORT_DEBUG_DRAW_OCCLUDERS,
        VIEWPORT_DEBUG_DRAW_MOTION_VECTORS,
    };
}
