namespace Godot.Net.Core.OS;

public enum MainLoopNotificationType
{
    //make sure these are replicated in Node
    NOTIFICATION_APPLICATION_FOCUS_IN  = 2016,
    NOTIFICATION_APPLICATION_FOCUS_OUT = 2017,
    NOTIFICATION_APPLICATION_PAUSED    = 2015,
    NOTIFICATION_APPLICATION_RESUMED   = 2014,
    NOTIFICATION_CRASH                 = 2012,
    NOTIFICATION_OS_IME_UPDATE         = 2013,
    NOTIFICATION_OS_MEMORY_WARNING     = 2009,
    NOTIFICATION_TEXT_SERVER_CHANGED   = 2018,
    NOTIFICATION_TRANSFORM_CHANGED     = 2000,
    NOTIFICATION_TRANSLATION_CHANGED   = 2010,
    NOTIFICATION_WM_ABOUT              = 2011,
}
