namespace Godot.Net.Drivers.GLES3.Storage;

public enum DefaultGLTexture
{
    DEFAULT_GL_TEXTURE_WHITE,
    DEFAULT_GL_TEXTURE_BLACK,
    DEFAULT_GL_TEXTURE_TRANSPARENT,
    DEFAULT_GL_TEXTURE_NORMAL,
    DEFAULT_GL_TEXTURE_ANISO,
    DEFAULT_GL_TEXTURE_DEPTH,
    DEFAULT_GL_TEXTURE_CUBEMAP_BLACK,
    //DEFAULT_GL_TEXTURE_CUBEMAP_ARRAY_BLACK, // Cubemap Arrays not supported in GL 3.3 or GL ES 3.0
    DEFAULT_GL_TEXTURE_CUBEMAP_WHITE,
    DEFAULT_GL_TEXTURE_3D_WHITE,
    DEFAULT_GL_TEXTURE_3D_BLACK,
    DEFAULT_GL_TEXTURE_2D_ARRAY_WHITE,
    DEFAULT_GL_TEXTURE_2D_UINT,
    DEFAULT_GL_TEXTURE_MAX
};
