namespace Godot.Net.Core.Enums;

[Flags]
public enum InlineAlignment
{
    // Image alignment points.
    INLINE_ALIGNMENT_TOP_TO      = 0b0000,
    INLINE_ALIGNMENT_CENTER_TO   = 0b0001,
    INLINE_ALIGNMENT_BASELINE_TO = 0b0011,
    INLINE_ALIGNMENT_BOTTOM_TO   = 0b0010,
    INLINE_ALIGNMENT_IMAGE_MASK  = INLINE_ALIGNMENT_BASELINE_TO,

    // Text alignment points.
    INLINE_ALIGNMENT_TO_TOP      = INLINE_ALIGNMENT_BASELINE_TO,
    INLINE_ALIGNMENT_TO_CENTER   = 0b0100,
    INLINE_ALIGNMENT_TO_BASELINE = 0b1000,
    INLINE_ALIGNMENT_TO_BOTTOM   = 0b1100,
    INLINE_ALIGNMENT_TEXT_MASK   = INLINE_ALIGNMENT_TO_BOTTOM,

    // Presets.
    INLINE_ALIGNMENT_TOP         = INLINE_ALIGNMENT_BASELINE_TO,
    INLINE_ALIGNMENT_CENTER      = INLINE_ALIGNMENT_CENTER_TO | INLINE_ALIGNMENT_TO_CENTER,
    INLINE_ALIGNMENT_BOTTOM      = INLINE_ALIGNMENT_BOTTOM_TO | INLINE_ALIGNMENT_TO_BOTTOM
}
