namespace Godot.Net.Servers.Rendering.Storage;

public partial class Dependency
{
    public enum DependencyChangedNotification
    {
        DEPENDENCY_CHANGED_AABB,
        DEPENDENCY_CHANGED_MATERIAL,
        DEPENDENCY_CHANGED_MESH,
        DEPENDENCY_CHANGED_MULTIMESH,
        DEPENDENCY_CHANGED_MULTIMESH_VISIBLE_INSTANCES,
        DEPENDENCY_CHANGED_PARTICLES,
        DEPENDENCY_CHANGED_DECAL,
        DEPENDENCY_CHANGED_SKELETON_DATA,
        DEPENDENCY_CHANGED_SKELETON_BONES,
        DEPENDENCY_CHANGED_LIGHT,
        DEPENDENCY_CHANGED_LIGHT_SOFT_SHADOW_AND_PROJECTOR,
        DEPENDENCY_CHANGED_REFLECTION_PROBE,
    }
}
